apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wtqtz42aw-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wtqtz42aw-nodejs 
  name: wtqtz42aw-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: wtqtz42aw-nodejs 
