apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: wtqtz42aw-nodejs-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/wtqtz42aw-nodejs-gitops